services:
  - type: web
    name: invoice-processor
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /status
    envVars:
      - key: PORT
        value: 8000
    disk:
      size: 1GB
